### ISSUE TITLE
Improving clarity at https://github.com/fyne-io/docs.fyne.io/blob/main/started/index.md to avoid "could not find gcc or clang compilers" issues.

### ISSUE THREAD

**Issue by Manabarb** [fyne-io/docs.fyne.io#18]
### Description
Problem 1:
\bin on the \msys64\mingw64 folder is empty even after using the command "pacman -S mingw-w64-ucrt-x86_64-gcc", there are no instructions either on the "https://www.msys2.org/" main page or "https://docs.fyne.io/started/" to install the "msys64\mingw64" version if there's one, therefore "Fyne Setup.exe" will fail the c compiler check.
Bandaid:
https://discuss.codecademy.com/t/problem-with-msys2-cannot-add-path-to-environment-variables-no-mingw64-bin-folder-after-install/656816/7

Problem 2: 
Instructions assume the default folder will be selected for the installation of msys2, but do not say that it is just the default folder, therefore people who do not choose  “C:\msys64\" as the install folder but find the bandaid will still fail the compiler check, the instructions do not prompt the user to check which folder they selected to install it either.

Problem 3: "go get fyne.io/fyne/v2@latest" does not work outside modules, "go install fyne.io/fyne/v2/cmd/fyne@latest" does but they are not separated in any way, as if both commands were required to be used in sequence, or both able to be used in any kind of situation, while each has their own use. Splitting "go install fyne.io/fyne/v2/cmd/fyne@latest" from the "modules" instruction section into it's own area would add clarity to the steps.

**Comment by andydotxyz** [comment]
Problem 1:

The step "Open “MSYS2 MinGW 64-bit” from the start menu" is critical - if you open the right terminal then it will all be installed and set up correctly.

Problem 2:

Can't we assume that people who choose a non-standard location will know that is the folder to specify when pasting in the commands?

Problem 3:

The previous step in the text literally initialise a go module and change into the right directory. So it will work if the steps are followed...

**Comment by andydotxyz** [comment]
I have removed the references to legacy / non-modules Go as that is no longer supported and could lead to confusion.

**Comment by Manabarb** [comment]
Thank you.
~~ I think #1 is a problem of the pack being installed on the "https://www.msys2.org/" webpage giving instructions on installing mingw-w64-ucrt-x86_64-gcc, but~~  actually nvm, i realize i skipped the  "$ pacman -S git mingw-w64-x86_64-toolchain" step on the getting started page, my bad, but probably I'm not the only one since i found the bandaid.
#2 I was just thinking that maybe a small warning/comment about the installation possibly not being on the default folder would help people who changed the folder to not get confused and keep the folder they actually installed their stuff in in mind.
#3 i was hoping using a module would not be required but apparently it's mandatory in order to import fyne at all unless you manage to get it on Go's Root folder.

**Comment by andydotxyz** [comment]
> P 3: I was hoping using a module would not be required but apparently it's mandatory in order to import fyne at all unless you manage to get it on Go's Root folder.

There is no unless here - modules are now mandatory with any Go app.

**Comment by andydotxyz** [comment]
> P 2: I was just thinking that maybe a small warning/comment about the installation possibly not being on the default folder would help people who changed the folder to not get confused and keep the folder they actually installed their stuff in in mind.

If you can think of a way that this could be helped do please open a pull request on the [fyne-io/docs.fyne.io](/fyne-io/docs.fyne.io) repository.
