### ISSUE TITLE
Add a light mode

### ISSUE THREAD

**Issue by pjanx** [fyne-io/docs.fyne.io#36]
### Description
All of my system and websites I use are black on white, and I think the website should [respect a user's preferences](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

Moreover, this is just jarring:

![image](https://github.com/user-attachments/assets/ef95701b-5917-4c5d-aa5d-e455d32e973c)

[Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) config as a workaround (excuse me, my motivation ends here):
```
@-moz-document domain("docs.fyne.io") {
    body, table, a, .navbar-default, .panel { color: black !important; background: white !important; }
    .panel-heading, .panel-heading a { background: #eee !important; }
}
```

**Comment by andydotxyz** [comment]
Many thanks, I wrapped those settings in a `@media (prefers-color-scheme: light)` and we are good to go.
New site is generating now.
