### ISSUE TITLE
"Getting Started" side-navigation becomes hidden when searchbar in top-navigation wraps

### ISSUE THREAD

**Issue by Gambloide** [fyne-io/docs.fyne.io#6]
See screenshot:

![image](https://github.com/fyne-io/docs.fyne.io/assets/5939852/d417f01a-64fc-4c3b-ab42-8f6ed74a60db)

The barely still visible "button" for the Getting Started section also becomes inaccessible with pointing devices like this, since only the text is intractable, not the whole element.

**Comment by andydotxyz** [comment]
Oh good catch, that should not wrap - thanks!

**Comment by andydotxyz** [comment]
Put in a temporary fix to hide search when there is not room
