### ISSUE TITLE
Search doesn't seem to find everything

### ISSUE THREAD

**Issue by sdassow** [fyne-io/docs.fyne.io#9]
### Description

Something with the new search is still off - searching for "canvas" for example does not include the page 'Fyne API "canvas"' or "Canvas and CanvasObject", which might be considered the most relevant when trying to look for it. Same goes for other search terms like "package" which does not include the page "Packaging for Desktop", which is also highly relevant as a search result.

**Comment by andydotxyz** [comment]
Thanks. I think the new algorithm is running on alphabetic order of result titles instead of relevance.
The missing pages are in the index, but not shown high enough in the results to be visible.

We should look into how to fix this!

**Comment by sdassow** [comment]
In terms of UX, I was initially expecting that pressing ENTER would lead me to the full search results page.
Maybe having both makes sense? Otherwise the result scoring could always get in the way of potentially useful search hits.

**Comment by andydotxyz** [comment]
Ah yes the full results page, I wonder where that went...

**Comment by sdassow** [comment]
With a maximum of five results this seems very restricted, and dependent on manual tuning. Looking at the example search for "package", it's currently not giving any relevant results at the top. On a full search results page I could just scroll down further and find them anyways.
I'm currently doing "git grep" in the docs repo to work around it, even though that isn't a great user experience.

**Comment by andydotxyz** [comment]
You're right the full page search provided much more - this is back finally!
